# Etapa de compilación
FROM cirrusci/flutter:stable AS build

WORKDIR /app

COPY . .

RUN flutter channel stable
RUN flutter upgrade
RUN flutter config --enable-web
RUN flutter pub get
RUN flutter build web

# Etapa de producción (nginx)
FROM nginx:alpine

COPY --from=build /app/build/web /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
